apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-53ws
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-53ws
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-53ws
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-53ws
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-53ws
    spec:
      containers:
      - image: quay.io/qijing/ex-registry-xeiv-tenant/appstudio/dc-metro-map-53ws@sha256:40dd8fdbb960a0a7ec2cc441bf05e8c8ebd1abfc7cb7c8d99dc193d84c8ab0d5
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
